spring:
  jpa:
    # maybe, it will be needed in the future
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

    # maybe, it will be needed in the future
    hibernate:
      ddl-auto: update
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: secretpassword